import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const getStyles = theme =>
  StyleSheet.create({
    // Performance optimized styles for animations
    backgroundContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: screenWidth,
      height: screenHeight,
    },
    floatingShape1: {
      position: 'absolute',
      width: 200,
      height: 200,
      top: '15%',
      left: '70%',
      borderRadius: 100,
      backgroundColor: 'rgba(60, 79, 224, 0.08)',
    },
    floatingShape2: {
      position: 'absolute',
      width: 150,
      height: 150,
      bottom: '30%',
      right: '80%',
      borderRadius: 75,
      backgroundColor: 'rgba(16, 185, 129, 0.08)',
    },
    floatingShape3: {
      position: 'absolute',
      width: 120,
      height: 120,
      top: '60%',
      left: '80%',
      borderRadius: 60,
      backgroundColor: 'rgba(245, 158, 11, 0.08)',
    },
    container: {
      flex: 1,
      backgroundColor: theme?.colors?.background?.primary || '#FFFFFF',
    },
    // Header styles inspired by LandingScreen
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingTop: theme?.spacing?.[4] || 16,
      paddingBottom: theme?.spacing?.[2] || 8,
    },
    headerLogo: {
      fontSize: 20,
      fontWeight: '700',
      color: theme?.colors?.text?.primary || '#1E293B',
    },
    headerSignUp: {
      fontSize: 14,
      fontWeight: '500',
      color: theme?.colors?.text?.primary || '#1E293B',
      paddingHorizontal: theme?.spacing?.[3] || 12,
      paddingVertical: theme?.spacing?.[2] || 8,
      borderRadius: theme?.borderRadius?.lg || 12,
      backgroundColor: theme?.colors?.background?.secondary || '#F8FAFC',
    },
    headerLogoIconCircle: {
      backgroundColor: '#3C4FE0',
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    // Brand row inspired by LandingScreen
    brandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingVertical: theme?.spacing?.[3] || 12,
    },
    brandIcon: {
      backgroundColor: theme?.colors?.accent?.green || '#10B981',
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: theme?.spacing?.[3] || 12,
      ...(theme?.shadows?.sm || {}),
    },
    brandName: {
      fontWeight: '700',
      fontSize: 16,
      color: theme?.colors?.text?.primary || '#1E293B',
    },
    brandTagline: {
      fontSize: 12,
      color: theme?.colors?.text?.secondary || '#64748B',
    },
    // Hero section with improved typography
    heroContainer: {
      alignItems: 'center',
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingTop: theme?.spacing?.[8] || 32,
      paddingBottom: theme?.spacing?.[6] || 24,
    },
    heroInner: {
      maxWidth: 400,
      alignSelf: 'center',
      width: '100%',
      alignItems: 'center',
    },
    heroTitle: {
      fontSize: 32,
      fontWeight: '800',
      textAlign: 'center',
      color: theme?.colors?.accent?.green || '#22C55E',
      marginBottom: theme?.spacing?.[2] || 8,
    },
    heroSubtitle: {
      fontSize: 32,
      fontWeight: '800',
      textAlign: 'center',
      color: theme?.colors?.accent?.green || '#22C55E',
      marginBottom: theme?.spacing?.[3] || 12,
    },
    heroDescription: {
      fontSize: 16,
      color: theme?.colors?.text?.primary || '#1E293B',
      textAlign: 'center',
      marginBottom: theme?.spacing?.[2] || 8,
    },
    heroSmallText: {
      fontSize: 14,
      color: theme?.colors?.text?.secondary || '#64748B',
      textAlign: 'center',
      marginBottom: theme?.spacing?.[6] || 24,
    },
    heroGradientBg: { width: '100%', borderRadius: 24, overflow: 'hidden' },
    heroCtaButton: {
      marginTop: 16,
      borderRadius: 32,
      backgroundColor: '#3C4FE0',
      shadowColor: '#3C4FE0',
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    heroCtaButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroCtaButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
    // Rocket card inspired by LandingScreen
    rocketCard: {
      backgroundColor: theme?.colors?.accent?.green
        ? `${theme.colors.accent.green}20`
        : '#D1FAE5',
      width: 72,
      height: 72,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      marginBottom: theme?.spacing?.[6] || 24,
      ...(theme?.shadows?.sm || {}),
    },
    // Stats section with improved design
    statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingVertical: theme?.spacing?.[4] || 16,
      gap: theme?.spacing?.[2] || 8,
    },
    statCard: {
      flex: 1,
      backgroundColor: theme?.colors?.surface?.card || '#FFFFFF',
      borderRadius: 16,
      padding: theme?.spacing?.[3] || 12,
      alignItems: 'center',
      marginHorizontal: theme?.spacing?.[1] || 4,
      ...(theme?.shadows?.sm || {}),
      borderWidth: 1,
      borderColor: theme?.colors?.border?.primary || '#E2E8F0',
    },
    statNumber: {
      fontSize: 18,
      fontWeight: '700',
      color: theme?.colors?.text?.primary || '#1E293B',
      marginTop: theme?.spacing?.[1] || 4,
      marginBottom: theme?.spacing?.[1] || 4,
    },
    statLabel: {
      fontSize: 12,
      color: theme?.colors?.text?.secondary || '#64748B',
      textAlign: 'center',
    },
    // Auth card with improved styling
    authCardContainer: {
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingVertical: theme?.spacing?.[6] || 24,
    },
    authCard: {
      maxWidth: 420,
      alignSelf: 'center',
      width: '100%',
      backgroundColor: '#fff',
      borderRadius: 24,
      padding: 28,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    authCardHeader: {
      alignItems: 'center',
      marginBottom: 20,
    },
    authCardHeaderTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#0F172A',
      textAlign: 'center',
    },
    authCardHeaderSubtitle: {
      fontSize: 16,
      color: '#64748B',
      textAlign: 'center',
      marginTop: 6,
    },
    authCardBody: {
      gap: theme?.spacing?.[4] || 16,
    },
    authCardButton: {
      borderRadius: 999,
      overflow: 'hidden',
      marginTop: 8,
      marginBottom: 18,
      height: 54,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 0,
      shadowColor: '#10B981',
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
    authButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    authButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 20,
      letterSpacing: 0.2,
    },
    dividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 18,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: '#E5E7EB',
    },
    dividerText: {
      marginHorizontal: 12,
      fontSize: 12,
      color: '#94A3B8',
      textTransform: 'uppercase',
      fontWeight: '600',
      letterSpacing: 1,
    },
    socialButtonsContainer: {
      gap: 14,
      marginBottom: 10,
    },
    socialButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderColor: '#E5E7EB',
      borderWidth: 1,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 18,
      marginBottom: 0,
      marginTop: 0,
      marginRight: 0,
      marginLeft: 0,
      marginVertical: 0,
    },
    socialButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    socialButtonText: {
      color: '#0F172A',
      fontWeight: '600',
      fontSize: 16,
      marginLeft: 10,
    },
    agreementText: {
      fontSize: 12,
      textAlign: 'center',
      color: '#94A3B8',
      marginTop: 18,
    },
    agreementLink: {
      color: '#10B981',
      fontWeight: '600',
      textDecorationLine: 'underline',
    },
    // Features section with improved design
    featuresContainer: {
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingVertical: theme?.spacing?.[6] || 24,
    },
    featuresInner: {
      maxWidth: 400,
      alignSelf: 'center',
      width: '100%',
    },
    featuresTitle: {
      fontSize: 20,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: theme?.spacing?.[6] || 24,
      color: theme?.colors?.text?.primary || '#1E293B',
    },
    featuresGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme?.spacing?.[3] || 12,
      justifyContent: 'space-between',
    },
    featureCard: {
      width: '47%',
      backgroundColor: theme?.colors?.surface?.card || '#FFFFFF',
      borderRadius: 16,
      padding: theme?.spacing?.[4] || 16,
      alignItems: 'center',
      gap: theme?.spacing?.[3] || 12,
      ...(theme?.shadows?.sm || {}),
      borderWidth: 1,
      borderColor: theme?.colors?.border?.primary || '#E2E8F0',
    },
    featureIcon: {
      width: 48,
      height: 48,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      ...(theme?.shadows?.sm || {}),
    },
    featureTitle: {
      fontWeight: '600',
      fontSize: 14,
      color: theme?.colors?.text?.primary || '#1E293B',
      textAlign: 'center',
    },
    featureDescription: {
      fontSize: 12,
      color: theme?.colors?.text?.secondary || '#64748B',
      textAlign: 'center',
    },
    // Bottom CTA with improved styling
    bottomCtaContainer: {
      marginTop: theme?.spacing?.[8] || 32,
      alignItems: 'center',
      paddingHorizontal: theme?.spacing?.[4] || 16,
      paddingBottom: theme?.spacing?.[6] || 24,
    },
    bottomCtaText: {
      fontSize: 16,
      color: theme?.colors?.text?.primary || '#1E293B',
      textAlign: 'center',
      marginBottom: theme?.spacing?.[2] || 8,
    },
    bottomCtaButton: {
      marginTop: 8,
      borderRadius: 24,
      backgroundColor: theme?.colors?.primary?.main || '#3C4FE0',
      paddingHorizontal: 24,
      paddingVertical: 12,
    },
    bottomCtaButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 16,
    },
  }); 