export const popularJobs = [
  {
    id: 1,
    company: 'TechVibe Studios',
    logo: 'briefcase',
    title: 'Frontend Developer',
    salary: '₹12,00,000 – ₹18,00,000/year',
    type: 'Full Time',
    time: '2 hours ago',
    color: ['#3B82F6', '#2563EB'],
    location: 'Bangalore',
    bookmarked: false,
  },
  {
    id: 2,
    company: 'GrowthHack Co',
    logo: 'trending-up',
    title: 'Growth Marketer',
    salary: '₹9,00,000 – ₹14,00,000/year',
    type: 'Full Time',
    time: '1 hour ago',
    color: ['#10B981', '#059669'],
    location: 'Remote',
    bookmarked: true,
  },
  {
    id: 3,
    company: 'Designify',
    logo: 'pen-tool',
    title: 'UI/UX Designer',
    salary: '₹8,00,000 – ₹12,00,000/year',
    type: 'Part Time',
    time: '30 min ago',
    color: ['#6366F1', '#8B5CF6'],
    location: 'Delhi',
    bookmarked: false,
  },
  {
    id: 4,
    company: 'FinEdge',
    logo: 'dollar-sign',
    title: 'Finance Analyst',
    salary: '₹10,00,000 – ₹16,00,000/year',
    type: 'Full Time',
    time: '4 hours ago',
    color: ['#F59E42', '#FBBF24'],
    location: 'Mumbai',
    bookmarked: false,
  },
];

export const recentJobs = [
  {
    id: 5,
    company: 'TechVibe Studios',
    logo: 'briefcase',
    title: 'Backend Developer',
    salary: '₹13,00,000 – ₹19,00,000/year',
    type: 'Full Time',
    time: '2 hours ago',
    location: 'Bangalore',
    bookmarked: false,
  },
  {
    id: 6,
    company: 'GrowthHack Co',
    logo: 'trending-up',
    title: 'SEO Specialist',
    salary: '₹7,00,000 – ₹10,00,000/year',
    type: 'Part Time',
    time: '1 hour ago',
    location: 'Remote',
    bookmarked: true,
  },
  {
    id: 7,
    company: 'Designify',
    logo: 'pen-tool',
    title: 'Graphic Designer',
    salary: '₹6,00,000 – ₹9,00,000/year',
    type: 'Full Time',
    time: '30 min ago',
    location: 'Delhi',
    bookmarked: false,
  },
  {
    id: 8,
    company: 'FinEdge',
    logo: 'dollar-sign',
    title: 'Accountant',
    salary: '₹8,00,000 – ₹12,00,000/year',
    type: 'Full Time',
    time: '4 hours ago',
    location: 'Mumbai',
    bookmarked: false,
  },
];
