import { StyleSheet } from 'react-native';

export const getStyles = theme =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    scrollView: {
      flex: 1,
    },
    scrollViewContent: {
      paddingBottom: 40,
    },

    // Header Styles - Ultra soft and premium
    headerContainer: {
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 16,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 3,
      borderWidth: 1,
      borderColor: '#F5F5F5',
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    backButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#F8FAFC',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#F0F0F0',
    },
    headerTitleContainer: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: '600',
      color: '#212121',
      marginBottom: 6,
      textAlign: 'center',
      fontFamily: 'System',
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: 16,
      color: '#9E9E9E',
      fontWeight: '500',
      textAlign: 'center',
      fontFamily: 'System',
      letterSpacing: -0.3,
      lineHeight: 22,
    },
    logoutButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FEF7F7',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#F0F0F0',
    },

    // Search Styles - Ultra soft and premium
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 16,
      gap: 18,
    },
    searchInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F1F3F4',
      borderRadius: 24,
      paddingHorizontal: 22,
      height: 58,
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#F0F0F0',
      gap: 16,
    },
    searchInput: {
      flex: 1,
      fontSize: 17,
      color: '#212121',
      fontWeight: '500',
      fontFamily: 'System',
      letterSpacing: -0.3,
    },
    filterButton: {
      width: 58,
      height: 58,
      borderRadius: 24,
      backgroundColor: '#E3F2FD',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#E0F2FE',
    },

    // Error Styles
    errorContainer: {
      backgroundColor: '#FEF2F2',
      borderWidth: 1,
      borderColor: '#FECACA',
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingVertical: 16,
      marginHorizontal: 24,
      marginBottom: 20,
      shadowColor: '#E0E0E0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    errorText: {
      fontSize: 16,
      color: '#DC2626',
      fontWeight: '500',
      textAlign: 'center',
      fontFamily: 'System',
    },

    // No Results Styles
    noResultsContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      paddingVertical: 60,
    },
    noResultsText: {
      fontSize: 20,
      color: '#212121',
      fontWeight: '600',
      textAlign: 'center',
      marginTop: 16,
      marginBottom: 8,
      fontFamily: 'System',
      letterSpacing: -0.3,
    },
    noResultsSubtext: {
      fontSize: 16,
      color: '#9E9E9E',
      fontWeight: '400',
      textAlign: 'center',
      fontFamily: 'System',
      letterSpacing: -0.2,
    },

    // Section Styles - Enhanced soft typography
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 22,
    },
    sectionTitle: {
      fontSize: 24,
      fontWeight: '600',
      color: '#212121',
      fontFamily: 'System',
      letterSpacing: -0.5,
    },
    seeAllText: {
      fontSize: 16,
      color: '#3949AB',
      fontWeight: '600',
      fontFamily: 'System',
      letterSpacing: -0.3,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: '#E3F2FD',
      overflow: 'hidden',
    },

    // Popular Jobs Styles - Enhanced soft spacing and curves
    popularJobsContainer: {
      paddingBottom: 36,
      paddingHorizontal: 24,
    },
    popularJobsScroll: {
      paddingLeft: 0,
      paddingRight: 20,
    },

    // Recent Jobs Styles - Enhanced soft spacing
    recentJobsContainer: {
      paddingHorizontal: 24,
      paddingBottom: 36,
    },
    recentJobsList: {
      gap: 20,
    },
  });
